package com.jamesg.Database2Application.domain.entities;
// POJO: Plain Old Java Object -> now converted to a JPA entity
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity // Labels this object as a JPA entity
@Table(name = "authors") // Specifies the table this maps to in the database
public class AuthorEntity {

    @Id // Specifies the primary key on the table
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "author_id_seq") // Specifies that this field is auto-generated by the database (1, 2, 3, ...)
    private Long id; // Long so it can be null

    private String name;

    private Integer age; // Integer so it can be null

}
